[build]
command = "jekyll build"
publish = "_site"

[[redirects]]
  from = "/el-aerogenerador-mas-grande-y-potente-del-mundo-comienza-a-construirse-en-china/"
  to = "crypto/el-aerogenerador-mas-grande-y-potente-del-mundo-comienza-a-construirse-en-china/"
  status = 301

