[build]
command = "jekyll build"
publish = "_site"

[redirects]
  from = "https://master--incredible-parsley-b9433.netlify.app/"
  to = "https://focustecno.com/"
  status = 301
  force = true
  query = {path = ":path"}
